(() => {
const EXT_KEY="healthyEatingAlpha04Extensions";
const ext=Object.assign({daily:{date:"",cal:0,water:0,protein:0,fat:0,carbs:0,fibre:0,sugar:0,sodium:0,steps:0},exercise:[],shopping:[],family:{enabled:false,name:"",email:""},connections:{}},JSON.parse(localStorage.getItem(EXT_KEY)||"{}"));
const saveExt=()=>localStorage.setItem(EXT_KEY,JSON.stringify(ext));
const by=id=>document.getElementById(id);
const val=id=>by(id)?.value||"";
const num=id=>Number(val(id))||0;
const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));

// Postal address controls and persistence
const postalSame=by("postal-same"), postalFields=by("postal-fields");
function togglePostal(){ postalFields?.classList.toggle("hidden",postalSame?.checked); }
postalSame?.addEventListener("change",togglePostal); togglePostal();

// Extended profile data is stored inside the main Alpha 0.4 record whenever the user continues.
by("personal-next")?.addEventListener("click",()=>{ setTimeout(()=>{ try{const d=JSON.parse(localStorage.getItem("healthyEatingAlpha04")); if(!d)return; d.personal=Object.assign(d.personal||{},{postalSame:postalSame.checked,postalCountry:val("postal-country"),postalRegion:val("postal-region"),postalPostcode:val("postal-postcode"),postalSuburb:val("postal-suburb"),postalStreet:val("postal-street")}); localStorage.setItem("healthyEatingAlpha04",JSON.stringify(d));}catch(e){} },20); });

const dietaryIds=["food-allergies","food-intolerances","medical-restrictions","eating-pattern","pregnancy-status","cultural-restrictions","foods-love","foods-like","foods-dislike","foods-never","food-context"];
by("calculate-button")?.addEventListener("click",()=>{setTimeout(()=>{try{const d=JSON.parse(localStorage.getItem("healthyEatingAlpha04"));if(!d)return;d.dietary=Object.fromEntries(dietaryIds.map(id=>[id,val(id)]));localStorage.setItem("healthyEatingAlpha04",JSON.stringify(d));}catch(e){}},20)});
function loadExtras(){try{const d=JSON.parse(localStorage.getItem("healthyEatingAlpha04")); if(!d)return; const p=d.personal||{}; if(by("postal-same")){by("postal-same").checked=p.postalSame!==false;["country","region","postcode","suburb","street"].forEach(k=>{const el=by("postal-"+k);if(el)el.value=p["postal"+k[0].toUpperCase()+k.slice(1)]||""});togglePostal();} const dietary=d.dietary||{};dietaryIds.forEach(id=>{if(by(id))by(id).value=dietary[id]||""});}catch(e){}}
setTimeout(loadExtras,100);

// Feature navigation
function openFeature(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));by(id)?.classList.add("active");window.scrollTo(0,0);if(id==="daily-progress")renderDaily();if(id==="exercise-log")renderExercise();if(id==="progress-history")renderHistory(30);if(id==="shopping-list")renderShopping();if(id==="food-preferences")renderFoodPrefs();if(id==="family-connections")renderConnections();}
document.addEventListener("click",e=>{const b=e.target.closest("[data-open-feature]");if(b)openFeature(b.dataset.openFeature)});

function goals(){try{const d=JSON.parse(localStorage.getItem("healthyEatingAlpha04"))||{};const r=d.recommendations||{};return {cal:Math.round((r.energyKj||8368)/4.184),water:r.waterMl||2200,protein:r.protein||100,fat:r.fat||70,carbs:r.carbs||250,fibre:30,sugar:50,sodium:2000,steps:10000};}catch(e){return {cal:2000,water:2200,protein:100,fat:70,carbs:250,fibre:30,sugar:50,sodium:2000,steps:10000}}}
function progressState(current,target,isLimit=false){const ratio=target?current/target:0;if(isLimit){if(ratio<.75)return "green";if(ratio<=1)return "yellow";return "red";}if(ratio>=.85&&ratio<=1.15)return "green";if(ratio>=.55)return "yellow";return "red";}
function renderDaily(){const g=goals();const labels={cal:"Energy",water:"Water",protein:"Protein",fat:"Fat",carbs:"Carbohydrate",fibre:"Fibre",sugar:"Sugar",sodium:"Sodium",steps:"Steps"};const units={cal:"Cal",water:"mL",protein:"g",fat:"g",carbs:"g",fibre:"g",sugar:"g",sodium:"mg",steps:""};by("daily-progress-grid").innerHTML=Object.keys(labels).map(k=>{const c=ext.daily[k]||0,t=g[k],limit=["sugar","sodium"].includes(k),state=progressState(c,t,limit),pct=Math.min(100,Math.round(c/t*100)||0);return `<div class="progress-card ${state}"><div><strong>${labels[k]}</strong><span>${c.toLocaleString()} / ${t.toLocaleString()} ${units[k]}</span></div><div class="progress-track"><i style="width:${pct}%"></i></div><small>${state==="green"?"Going well":state==="yellow"?"Nearly there or worth checking":"Needs review"}</small></div>`}).join("");["cal","water","protein","fat","carbs","fibre","sugar","sodium","steps"].forEach(k=>{const el=by("today-"+k);if(el)el.value=ext.daily[k]||""});}
by("save-daily-progress")?.addEventListener("click",()=>{ext.daily={date:new Date().toISOString().slice(0,10),cal:num("today-cal"),water:num("today-water"),protein:num("today-protein"),fat:num("today-fat"),carbs:num("today-carbs"),fibre:num("today-fibre"),sugar:num("today-sugar"),sodium:num("today-sodium"),steps:num("today-steps")};saveExt();renderDaily();});

function renderExercise(){by("exercise-history").innerHTML=ext.exercise.length?ext.exercise.slice().reverse().map((x,i)=>`<div class="list-row"><span>🏃</span><div><strong>${esc(x.name)}</strong><small>${x.minutes} min · ${x.intensity} · ${x.calories} Cal burned · ${x.credit} Cal credited</small><p>${esc(x.notes||"")}</p></div></div>`).join(""):"<p class='empty-state'>No extra activity logged yet.</p>";}
by("add-exercise")?.addEventListener("click",()=>{const name=val("exercise-name").trim();if(!name)return;const calories=num("exercise-calories"),choice=val("exercise-credit-choice");const credit=choice==="custom"?num("exercise-custom-credit"):Math.round(calories*Number(choice)/100);ext.exercise.push({date:new Date().toISOString(),name,minutes:num("exercise-minutes"),intensity:val("exercise-intensity"),calories,credit,notes:val("exercise-notes")});saveExt();renderExercise();["exercise-name","exercise-minutes","exercise-calories","exercise-custom-credit","exercise-notes"].forEach(id=>by(id).value="");});

function renderShopping(){const groups={};ext.shopping.forEach((x,i)=>(groups[x.category]??=[]).push({...x,i}));by("shopping-items").innerHTML=ext.shopping.length?Object.entries(groups).map(([cat,items])=>`<h4>${esc(cat)}</h4>${items.map(x=>`<label class="shopping-row ${x.done?"done":""}"><input type="checkbox" data-shop-check="${x.i}" ${x.done?"checked":""}><span><strong>${esc(x.item)}</strong><small>${esc(x.quantity)} ${x.brand?"· "+esc(x.brand):""}</small></span><button data-shop-remove="${x.i}">Remove</button></label>`).join("")}`).join(""):"<p class='empty-state'>Your grocery list is empty.</p>";}
by("add-shopping-item")?.addEventListener("click",()=>{const item=val("shopping-item").trim();if(!item)return;const existing=ext.shopping.find(x=>x.item.toLowerCase()===item.toLowerCase()&&!x.done);if(existing){existing.quantity=[existing.quantity,val("shopping-quantity")].filter(Boolean).join(" + ");}else ext.shopping.push({item,quantity:val("shopping-quantity"),category:val("shopping-category"),brand:val("shopping-brand"),done:false});saveExt();renderShopping();by("shopping-item").value="";by("shopping-quantity").value="";});
document.addEventListener("change",e=>{if(e.target.dataset.shopCheck!==undefined){ext.shopping[Number(e.target.dataset.shopCheck)].done=e.target.checked;saveExt();renderShopping();}});document.addEventListener("click",e=>{if(e.target.dataset.shopRemove!==undefined){ext.shopping.splice(Number(e.target.dataset.shopRemove),1);saveExt();renderShopping();}});

function renderFoodPrefs(){try{const d=JSON.parse(localStorage.getItem("healthyEatingAlpha04"))||{},f=d.dietary||{};const rows=[["Love",f["foods-love"]],["Like",f["foods-like"]],["Dislike",f["foods-dislike"]],["Never eat",f["foods-never"]],["Conditional",f["food-context"]],["Allergies",f["food-allergies"]],["Medical restrictions",f["medical-restrictions"]]];by("food-preference-summary").innerHTML=rows.map(([a,b])=>`<div class="summary-line"><strong>${a}</strong><span>${esc(b||"Not entered")}</span></div>`).join("");}catch(e){}}
by("edit-food-profile")?.addEventListener("click",()=>{document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));by("health").classList.add("active");window.scrollTo(0,500);});

const connectionNames=["Apple Health & Apple Watch","Google Health Connect","Smart scales","Fitness trackers","Nutrition apps","Calendar & reminders","Social sharing"];
function renderConnections(){by("family-sharing-enabled").checked=ext.family.enabled;by("household-name").value=ext.family.name;by("family-email").value=ext.family.email;by("connections-list").innerHTML=connectionNames.map(n=>`<label class="connection-row"><span><strong>${n}</strong><small>Ready for a future secure connection</small></span><input type="checkbox" data-connection="${esc(n)}" ${ext.connections[n]?"checked":""}></label>`).join("");}
by("save-family")?.addEventListener("click",()=>{ext.family={enabled:by("family-sharing-enabled").checked,name:val("household-name"),email:val("family-email")};saveExt();});document.addEventListener("change",e=>{if(e.target.dataset.connection){ext.connections[e.target.dataset.connection]=e.target.checked;saveExt();}});

function renderHistory(days){let weights=[];try{const d=JSON.parse(localStorage.getItem("healthyEatingAlpha04"))||{};weights=d.weightHistory||[];}catch(e){}const cut=days==="all"?0:Date.now()-Number(days)*86400000;weights=weights.filter(x=>!cut||new Date(x.date).getTime()>=cut);const exercises=ext.exercise.filter(x=>!cut||new Date(x.date).getTime()>=cut);const totalCal=exercises.reduce((a,x)=>a+x.calories,0);by("history-summary").innerHTML=`<strong>${weights.length} weight entries · ${exercises.length} activities</strong><p>${totalCal.toLocaleString()} estimated exercise calories across this period.</p>`;const max=Math.max(...weights.map(x=>x.weightKg),1);by("history-bars").innerHTML=weights.length?weights.map(x=>`<div class="history-column"><i style="height:${Math.max(10,x.weightKg/max*180)}px"></i><small>${x.weightKg} kg<br>${esc(x.date)}</small></div>`).join(""):"<p class='empty-state'>Add weight check-ins to build your graph.</p>";}
document.querySelector(".history-period")?.addEventListener("click",e=>{if(e.target.dataset.period){document.querySelectorAll(".history-period button").forEach(b=>b.classList.toggle("active",b===e.target));renderHistory(e.target.dataset.period)}});
})();
