(()=>{
'use strict';
const $=id=>document.getElementById(id);
const screens=[...document.querySelectorAll('.screen')];
const STORE='lifestyleCompanionAlpha12Fresh';
const rooms={planner:{icon:'📅',label:'Planner',status:'coming'},food:{icon:'🥗',label:'Food & Nutrition',status:'available'},exercise:{icon:'👟',label:'Exercise',status:'coming'},journal:{icon:'📖',label:'Journal',status:'coming'},family:{icon:'👨‍👩‍👧',label:'Family',status:'coming'},budget:{icon:'💰',label:'Budget',status:'coming'},mylife:{icon:'❤️',label:'My Life',status:'coming'},settings:{icon:'⚙️',label:'Settings',status:'available'}};
const characters=[['🐵','Chimpanzee'],['🐴','Horse'],['🐶','Dog'],['🐮','Cow'],['🐨','Koala'],['🦉','Owl'],['🦊','Fox'],['🐻','Bear'],['🐰','Rabbit'],['🐯','Tiger'],['🦁','Lion'],['🐧','Penguin']];
const thoughts=['One small step is still progress.','You set the pace. I am here to help.','There is no wrong door—use Back whenever you need it.','A calm start often makes the whole day easier.'];
let state=load();let navStack=[];let step=1;let draft=newDraft();let voices=[];let selectedVoice='';let currentSpeech=null;let recordingTarget=null;let mediaRecorder=null;let recordedChunks=[];let placeholderAction=null;
function load(){
  try {
    return JSON.parse(localStorage.getItem(STORE)) || {profiles:[],active:null,analytics:{roomTaps:{},interest:{}}};
  } catch (error) {
    return {profiles:[],active:null,analytics:{roomTaps:{},interest:{}}};
  }
}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function newDraft(mode='voice'){return{id:crypto.randomUUID?.()||String(Date.now()),mode,guided:true,fullName:'',preferredName:'',dob:'',email:'',preferredPhonetic:'',companionName:'',companionPhonetic:'',character:'🐵',personality:'calm',voiceURI:'',phones:[{type:'Mobile',country:'+61',number:''}],addresses:[{type:'Main address',value:''}],enabledRooms:['food'],nutrition:{weight:'',height:'',activity:'moderate',goal:'gradual',goalWeight:'',fasting:'none',waterReminders:false,dietary:''},pronunciation:{user:null,companion:null}}}
function active(){return state.profiles.find(p=>p.id===state.active)}
function show(id,push=true){const current=screens.find(s=>s.classList.contains('active'));if(push&&current&&current.id!==id)navStack.push(current.id);screens.forEach(s=>s.classList.toggle('active',s.id===id));if(id==='profiles')renderProfiles();if(id==='home')renderHome();if(id==='food-room')renderFood();if(id==='settings')renderSettings()}
function back(){const target=navStack.pop()||'home';show(target,false)}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function speak(text,voiceURI=selectedVoice){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-AU';const v=voices.find(x=>x.voiceURI===voiceURI);if(v)u.voice=v;currentSpeech=u;speechSynthesis.speak(u)}
function guide(text){$('guide-text').textContent=text;const name=draft.companionName||'Your Companion';$('guide-name').textContent=name;$('guide-avatar').textContent=draft.character||'🐵';if(draft.guided&&draft.mode==='voice')setTimeout(()=>speak(text,draft.voiceURI),150)}
function startSetup(mode){draft=newDraft(mode);step=1;navStack=[];show('wizard',false);renderWizard()}
function titles(){return[['Setup style','Choose how your Companion should guide you.'],['About you','Tell your Companion what you would like to be called.'],['Contact details','Optional details can be useful in future Rooms.'],['Your Companion','Choose a name, character and personality.'],['Companion voice','Listen first, then select the voice you prefer.'],['Your Rooms','Only selected Rooms ask extra setup questions.'],['Review','Check the main details before saving.']]}
function renderWizard(){document.querySelectorAll('.step').forEach(x=>x.classList.toggle('active',+x.dataset.step===step));const t=titles()[step-1];$('wizard-title').textContent=t[0];$('wizard-subtitle').textContent=t[1];$('wizard-progress').textContent=`${step} / 7`;$('prev-step').style.visibility=step===1?'hidden':'visible';$('next-step').textContent=step===7?'Create profile':'Continue';const guides=[
'Choose voice-guided setup to speak answers wherever possible, or typing setup to use the keyboard. You can swap methods at any time.',
'Tell me your full name and the name you want me to call you. The microphone button beside a field lets you speak the answer.',
'These details are optional. Add only what you are comfortable storing in this trial profile.',
'Choose what your Companion looks like and what you would like to call them. You can change everything later in Settings.',
'Press Play beside any voice. When you hear one you like, tick Select. A new sample stops the old sample immediately.',
'Every Room stays visible on Home. Tick Food and Nutrition only when you want to answer its health questions now.',
'Review your profile. When you create it, you will arrive at the Home Circle.'
];guide(guides[step-1]);if(step===3)renderContactEditors();if(step===5)renderVoices();if(step===6)renderRoomChecks();if(step===7)renderReview()}
function validate(){if(step===2){draft.fullName=$('full-name').value.trim();draft.preferredName=$('preferred-name').value.trim();draft.dob=$('dob').value;draft.email=$('email').value.trim();draft.preferredPhonetic=$('preferred-phonetic').value.trim();if(!draft.fullName||!draft.preferredName){toast('Please enter full name and preferred name.');return false}}if(step===4){draft.companionName=$('companion-name').value.trim();draft.companionPhonetic=$('companion-phonetic').value.trim();draft.personality=$('personality').value;if(!draft.companionName){toast('Please enter a Companion name.');return false}}if(step===5&&!draft.voiceURI){toast('Please select a Companion voice.');return false}if(step===6){syncRoomData()}return true}
function next(){if(!validate())return;if(step<7){step++;renderWizard()}else finish()}
function prev(){if(step>1){step--;renderWizard()}else show(state.profiles.length?'profiles':'welcome',false)}
function finish(){if(state.profiles.length>=10){toast('This trial supports up to 10 profiles.');return}state.profiles.push(JSON.parse(JSON.stringify(draft)));state.active=draft.id;save();renderHome();show('home',false);speak(`Hello ${draft.preferredPhonetic||draft.preferredName}. I am ${draft.companionPhonetic||draft.companionName}. We are ready to begin.`,draft.voiceURI)}
function populateForm(){['full-name','preferred-name','dob','email','preferred-phonetic','companion-name','companion-phonetic'].forEach(id=>{const map={'full-name':'fullName','preferred-name':'preferredName',dob:'dob',email:'email','preferred-phonetic':'preferredPhonetic','companion-name':'companionName','companion-phonetic':'companionPhonetic'};$(id).value=draft[map[id]]||''});$('guided-mode').checked=draft.guided;$('personality').value=draft.personality;renderCharacters()}
function renderCharacters(){$('character-grid').innerHTML=characters.map(([e,n])=>`<button class="character ${draft.character===e?'selected':''}" data-char="${e}" title="${n}">${e}</button>`).join('');document.querySelectorAll('[data-char]').forEach(b=>b.onclick=()=>{draft.character=b.dataset.char;renderCharacters();$('guide-avatar').textContent=draft.character})}
function renderVoices(){voices=speechSynthesis?.getVoices?.()||[];const au=voices.filter(v=>/en[-_]AU/i.test(v.lang));const list=(au.length?au:voices.filter(v=>/^en/i.test(v.lang))).slice(0,20);if(!list.length){$('voice-list').innerHTML='<p>No device voices are available yet. Wait a moment, then return to this page.</p>';return}$('voice-list').innerHTML=list.map(v=>`<div class="voice-row ${draft.voiceURI===v.voiceURI?'selected':''}"><div><b>${esc(v.name)}</b><small>${esc(v.lang)}${v.localService?' · On device':''}</small></div><button data-play-voice="${esc(v.voiceURI)}">▶ Play</button><label class="check-row"><input type="radio" name="voice" value="${esc(v.voiceURI)}" ${draft.voiceURI===v.voiceURI?'checked':''}> Select</label></div>`).join('');document.querySelectorAll('[data-play-voice]').forEach(b=>b.onclick=()=>{speechSynthesis.cancel();const v=voices.find(x=>x.voiceURI===b.dataset.playVoice);const user=draft.preferredPhonetic||draft.preferredName||'there';const comp=draft.companionPhonetic||draft.companionName||'your Companion';speak(`Hello ${user}. I am ${comp}. It is lovely to meet you.`,v?.voiceURI)});document.querySelectorAll('input[name="voice"]').forEach(r=>r.onchange=()=>{draft.voiceURI=r.value;selectedVoice=r.value;renderVoices()})}
function renderContactEditors(){$('phones-editor').innerHTML=draft.phones.map((p,i)=>`<div class="repeat-row"><label>Type<select data-phone-type="${i}">${['Mobile','Home','Business','Other'].map(x=>`<option ${p.type===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Number<div class="input-with-mic"><input data-phone-number="${i}" value="${esc(p.number)}" placeholder="0412 345 678"><button class="mic-field" data-phone-mic="${i}">🎤</button></div></label><button class="remove-row" data-remove-phone="${i}">Remove</button></div>`).join('');$('addresses-editor').innerHTML=draft.addresses.map((a,i)=>`<div class="repeat-row address-row"><label>Type<select data-address-type="${i}">${['Main address','Postal address','Business address','Holiday address','Other'].map(x=>`<option ${a.type===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Address<input data-address-value="${i}" value="${esc(a.value)}" autocomplete="street-address" placeholder="Start typing your address"></label><button class="remove-row" data-remove-address="${i}">Remove</button></div>`).join('');bindContactEditors()}
function bindContactEditors(){document.querySelectorAll('[data-phone-type]').forEach(x=>x.onchange=()=>draft.phones[+x.dataset.phoneType].type=x.value);document.querySelectorAll('[data-phone-number]').forEach(x=>x.oninput=()=>draft.phones[+x.dataset.phoneNumber].number=formatPhone(x.value));document.querySelectorAll('[data-address-type]').forEach(x=>x.onchange=()=>draft.addresses[+x.dataset.addressType].type=x.value);document.querySelectorAll('[data-address-value]').forEach(x=>x.oninput=()=>draft.addresses[+x.dataset.addressValue].value=x.value);document.querySelectorAll('[data-remove-phone]').forEach(x=>x.onclick=()=>{draft.phones.splice(+x.dataset.removePhone,1);renderContactEditors()});document.querySelectorAll('[data-remove-address]').forEach(x=>x.onclick=()=>{draft.addresses.splice(+x.dataset.removeAddress,1);renderContactEditors()});document.querySelectorAll('[data-phone-mic]').forEach(x=>x.onclick=()=>listenText(t=>{draft.phones[+x.dataset.phoneMic].number=formatPhone(t);renderContactEditors()}))}
function formatPhone(raw){let s=String(raw).replace(/[^\d+]/g,'');if(s.startsWith('0'))s='+61'+s.slice(1);if(s.startsWith('61'))s='+'+s;return s.replace(/(\+61)(\d)(\d{4})(\d{4}).*/,(_,a,b,c,d)=>`${a} ${b} ${c} ${d}`)}
function renderRoomChecks(){$('room-checks').innerHTML=Object.entries(rooms).filter(([id])=>id!=='settings').map(([id,r])=>`<label class="room-check"><span>${r.icon}</span><b>${r.label}</b><small>${r.status==='coming'?'Coming soon':''}</small><input type="checkbox" data-room-check="${id}" ${draft.enabledRooms.includes(id)?'checked':''}></label>`).join('');document.querySelectorAll('[data-room-check]').forEach(x=>x.onchange=()=>{const id=x.dataset.roomCheck;if(x.checked&&!draft.enabledRooms.includes(id))draft.enabledRooms.push(id);if(!x.checked)draft.enabledRooms=draft.enabledRooms.filter(r=>r!==id);$('food-questions').classList.toggle('hidden',!draft.enabledRooms.includes('food'))});$('food-questions').classList.toggle('hidden',!draft.enabledRooms.includes('food'));$('weight').value=draft.nutrition.weight;$('height').value=draft.nutrition.height;$('activity').value=draft.nutrition.activity;$('goal').value=draft.nutrition.goal;$('goal-weight').value=draft.nutrition.goalWeight;$('fasting').value=draft.nutrition.fasting;$('water-reminders').checked=draft.nutrition.waterReminders;$('dietary').value=draft.nutrition.dietary}
function syncRoomData(){draft.nutrition={weight:$('weight').value,height:$('height').value,activity:$('activity').value,goal:$('goal').value,goalWeight:$('goal-weight').value,fasting:$('fasting').value,waterReminders:$('water-reminders').checked,dietary:$('dietary').value.trim()}}
function renderReview(){$('review-avatar').textContent=draft.character;$('review-title').textContent=`${draft.preferredName} and ${draft.companionName}`;$('review-summary').innerHTML=`<div class="review-list"><div class="review-item"><b>Setup method:</b> ${draft.mode==='voice'?'Voice-guided':'Typing'}</div><div class="review-item"><b>Rooms ready now:</b> ${draft.enabledRooms.map(x=>rooms[x]?.label).filter(Boolean).join(', ')||'None'}</div><div class="review-item"><b>Contact entries:</b> ${draft.phones.filter(x=>x.number).length} phone number(s), ${draft.addresses.filter(x=>x.value).length} address(es)</div><div class="review-item"><b>Companion teaching:</b> ${draft.guided?'On':'Off'}</div></div>`}
function renderProfiles(){if(!state.profiles.length){$('profile-list').innerHTML='<div class="card"><p>No Alpha 1.2 profiles have been created on this device.</p></div>';return}$('profile-list').innerHTML=state.profiles.map(p=>`<div class="profile-card"><div class="avatar">${p.character}</div><div class="grow"><b>${esc(p.preferredName)}</b><small>${esc(p.companionName)} · ${p.mode==='voice'?'Voice setup':'Typed setup'}</small></div><div class="profile-card-actions"><button data-use="${p.id}">Use</button><button data-delete="${p.id}">Delete</button></div></div>`).join('');document.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{state.active=b.dataset.use;save();show('home')});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const p=state.profiles.find(x=>x.id===b.dataset.delete);if(confirm(`Delete the profile ${p.preferredName}? This cannot be undone.`)){state.profiles=state.profiles.filter(x=>x.id!==p.id);if(state.active===p.id)state.active=state.profiles[0]?.id||null;save();renderProfiles()}})}
function renderHome(){const p=active();if(!p)return show('profiles',false);$('home-greeting').textContent=`Good ${dayPart()}, ${p.preferredName}`;$('home-avatar').textContent=p.character;$('home-companion').textContent=p.companionName;$('profiles-button').textContent=p.character;$('thought').textContent=thoughts[Math.floor(Math.random()*thoughts.length)];document.querySelectorAll('[data-room]').forEach(b=>{const id=b.dataset.room;b.classList.toggle('active-room',id==='settings'||p.enabledRooms.includes(id));b.classList.toggle('coming',rooms[id].status==='coming')})}
function dayPart(){const h=new Date().getHours();return h<12?'morning':h<17?'afternoon':'evening'}
function renderFood(){const p=active();$('food-avatar').textContent=p.character;$('food-companion').textContent=p.companionName;$('food-note').textContent='A calm kitchen starts with a simple plan.'}
function openRoom(id){const p=active();state.analytics.roomTaps[id]=(state.analytics.roomTaps[id]||0)+1;save();if(id==='settings')return show('settings');if(rooms[id].status==='coming')return openPlaceholder(rooms[id].label,rooms[id].icon,`${rooms[id].label} is not operating yet. Your tap has been recorded locally as interest in this Room.`,'Notify me / Record interest',()=>{state.analytics.interest[id]=(state.analytics.interest[id]||0)+1;save();toast('Interest recorded on this device')});if(!p.enabledRooms.includes(id))return openPlaceholder(rooms[id].label,rooms[id].icon,`${p.companionName} can guide you through setting up this Room now.`,'Set up this Room',()=>{p.enabledRooms.push(id);save();toast(`${rooms[id].label} is now active`);show(id==='food'?'food-room':'home')});if(id==='food')show('food-room')}
function openPlaceholder(title,icon,copy,actionText,action){$('placeholder-title').textContent=title;$('placeholder-icon').textContent=icon;$('placeholder-heading').textContent=rooms[Object.keys(rooms).find(k=>rooms[k].label===title)]?.status==='coming'?'Coming soon':`Set up ${title}`;$('placeholder-copy').textContent=copy;$('placeholder-action').textContent=actionText;placeholderAction=action;show('placeholder')}
function renderSettings(){$('settings-detail').innerHTML='<p>Select an option above.</p>'}
function settingsView(type){const p=active();if(type==='profiles')return show('profiles');if(type==='guidance'){$('settings-detail').innerHTML=`<h3>Companion teaching</h3><label class="check-row"><input id="setting-guided" type="checkbox" ${p.guided?'checked':''}> Let ${esc(p.companionName)} explain pages and repeat instructions</label><button id="save-guidance" class="primary">Save</button>`;$('save-guidance').onclick=()=>{p.guided=$('setting-guided').checked;save();toast('Teaching preference saved')};return}if(type==='rooms'){$('settings-detail').innerHTML=`<h3>Manage Rooms</h3>${Object.entries(rooms).filter(([id])=>id!=='settings').map(([id,r])=>`<label class="room-check"><span>${r.icon}</span><b>${r.label}</b><small>${r.status==='coming'?'Coming soon':''}</small><input data-setting-room="${id}" type="checkbox" ${p.enabledRooms.includes(id)?'checked':''} ${r.status==='coming'?'disabled':''}></label>`).join('')}`;document.querySelectorAll('[data-setting-room]').forEach(x=>x.onchange=()=>{const id=x.dataset.settingRoom;if(x.checked&&!p.enabledRooms.includes(id))p.enabledRooms.push(id);if(!x.checked)p.enabledRooms=p.enabledRooms.filter(y=>y!==id);save()});return}if(type==='profile'){$('settings-detail').innerHTML=`<h3>Edit profile</h3><label>Full name<input id="edit-full" value="${esc(p.fullName)}"></label><label>Preferred name<input id="edit-preferred" value="${esc(p.preferredName)}"></label><label>Email<input id="edit-email" value="${esc(p.email||'')}"></label><button id="save-profile-edit" class="primary">Save profile</button>`;$('save-profile-edit').onclick=()=>{p.fullName=$('edit-full').value.trim();p.preferredName=$('edit-preferred').value.trim();p.email=$('edit-email').value.trim();save();toast('Profile saved')};return}if(type==='companion'){$('settings-detail').innerHTML=`<h3>Edit Companion</h3><label>Name<input id="edit-companion-name" value="${esc(p.companionName)}"></label><p>Character</p><div id="edit-character-grid" class="character-grid"></div><button id="save-companion-edit" class="primary">Save Companion</button>`;$('edit-character-grid').innerHTML=characters.map(([e,n])=>`<button class="character ${p.character===e?'selected':''}" data-edit-char="${e}" title="${n}">${e}</button>`).join('');let c=p.character;document.querySelectorAll('[data-edit-char]').forEach(b=>b.onclick=()=>{c=b.dataset.editChar;document.querySelectorAll('[data-edit-char]').forEach(x=>x.classList.toggle('selected',x.dataset.editChar===c))});$('save-companion-edit').onclick=()=>{p.companionName=$('edit-companion-name').value.trim()||p.companionName;p.character=c;save();toast('Companion saved')};return}}
function listenText(done){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){toast('Speech recognition is not available in this browser.');return}const r=new R();r.lang='en-AU';r.interimResults=false;toast('Listening…');r.onresult=e=>done(e.results[0][0].transcript);r.onerror=()=>toast('I could not hear that clearly.');r.start()}
function bindMicFields(){document.querySelectorAll('[data-listen]').forEach(b=>b.onclick=e=>{e.preventDefault();const id=b.dataset.listen;listenText(t=>{if(id==='dob')toast('For date of birth, please use the date picker in this prototype.');else $(id).value=t})})}
async function toggleRecording(target){if(mediaRecorder?.state==='recording'){mediaRecorder.stop();return}if(!navigator.mediaDevices?.getUserMedia){toast('Microphone recording is not supported here.');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});recordedChunks=[];recordingTarget=target;mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>recordedChunks.push(e.data);mediaRecorder.onstop=()=>{const blob=new Blob(recordedChunks,{type:mediaRecorder.mimeType});const reader=new FileReader();reader.onload=()=>{draft.pronunciation[target]=reader.result;const playId=target==='user'?'play-user-name':'play-companion-name';$(playId).disabled=false;toast('Pronunciation recording saved for this profile')};reader.readAsDataURL(blob);stream.getTracks().forEach(t=>t.stop())};mediaRecorder.start();toast('Recording… tap again to stop')}catch{toast('Microphone permission was not available.')}}
function playRecording(target){const src=draft.pronunciation[target];if(src)new Audio(src).play()}
function openVoice(){const p=active();$('voice-sheet-avatar').textContent=p.character;$('voice-sheet-title').textContent=`Speak to ${p.companionName}`;$('command-input').value='';$('voice-status').textContent='Tap the microphone or type below.';$('voice-sheet').classList.add('open')}
function handleCommand(text){const p=active(),c=text.toLowerCase().trim();if(!c)return toast('Please speak or type a command.');if(/food|nutrition/.test(c)){closeVoice();openRoom('food');speak('Opening Food and Nutrition.',p.voiceURI)}else if(/setting/.test(c)){closeVoice();show('settings');speak('Opening Settings.',p.voiceURI)}else if(/profile/.test(c)){closeVoice();show('profiles');speak('Opening Profiles.',p.voiceURI)}else if(/home|back/.test(c)){closeVoice();show('home');speak('Taking you home.',p.voiceURI)}else{speak('I heard you. This trial version understands only a few navigation commands so far.',p.voiceURI);$('voice-status').textContent='Command heard. More conversational ability comes in a later phase.'}}
function closeVoice(){$('voice-sheet').classList.remove('open')}
$('voice-setup').onclick=()=>startSetup('voice');$('typed-setup').onclick=()=>startSetup('typed');$('existing-profile').onclick=()=>show('profiles');$('new-profile').onclick=()=>startSetup('voice');$('wizard-back').onclick=prev;$('prev-step').onclick=prev;$('next-step').onclick=next;$('guided-mode').onchange=()=>draft.guided=$('guided-mode').checked;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{draft.mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('selected',x.dataset.mode===draft.mode));guide(draft.mode==='voice'?'Voice-guided setup selected. Use the microphone buttons beside answers.':'Typing setup selected. Use the keyboard to enter answers.')});$('repeat-guide').onclick=()=>speak($('guide-text').textContent,draft.voiceURI);$('add-phone').onclick=()=>{draft.phones.push({type:'Other',country:'+61',number:''});renderContactEditors()};$('add-address').onclick=()=>{draft.addresses.push({type:'Other',value:''});renderContactEditors()};$('record-user-name').onclick=()=>toggleRecording('user');$('record-companion-name').onclick=()=>toggleRecording('companion');$('play-user-name').onclick=()=>playRecording('user');$('play-companion-name').onclick=()=>playRecording('companion');$('profiles-button').onclick=()=>show('profiles');$('talk-centre').onclick=openVoice;$('food-talk').onclick=openVoice;$('new-thought').onclick=()=>renderHome();$('placeholder-action').onclick=()=>placeholderAction?.();$('close-voice').onclick=closeVoice;$('listen-command').onclick=()=>listenText(t=>{$('command-input').value=t;handleCommand(t)});$('send-command').onclick=()=>handleCommand($('command-input').value);$('reset-all').onclick=()=>{if(confirm('Delete every Alpha 1.2 profile and all trial data on this device?')){localStorage.removeItem(STORE);state=load();navStack=[];show('welcome',false);toast('All Alpha 1.2 trial data deleted')}};document.querySelectorAll('[data-back]').forEach(b=>b.onclick=back);document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>openRoom(b.dataset.room));document.querySelectorAll('[data-settings]').forEach(b=>b.onclick=()=>settingsView(b.dataset.settings));document.querySelectorAll('[data-open-settings]').forEach(b=>b.onclick=()=>show('settings'));document.querySelectorAll('.subroom:not([data-open-settings])').forEach(b=>b.onclick=()=>openPlaceholder(b.innerText.trim(),b.textContent.trim().charAt(0),'This feature is scheduled for the Food & Nutrition development sprint.','Back to Food & Nutrition',()=>show('food-room')));
if('speechSynthesis'in window){voices=speechSynthesis.getVoices();speechSynthesis.onvoiceschanged=()=>{voices=speechSynthesis.getVoices();if(step===5)renderVoices()}}if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});populateForm();bindMicFields();if(state.active&&active())show('home',false);else show('welcome',false);
})();
